-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrNdUHAFAYKqx+hpH
UCSVIEwUGAzGTCl2NlQfIBFZFTegCgYIKoZIzj0DAQehRANCAAQzKlbdAZeV1LW2
YjUrOf6peBRJslmQ7gCmiKCCL28VT8qJCTGHb0PEZrJn8Wi3xOCMR0fGY/EI/PJr
ltjo0hN0
-----END PRIVATE KEY-----