// Mocks generated by Mockito 5.4.2 from annotations
// in awad_nahas/test/features/products/mockito_data/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i13;
import 'dart:typed_data' as _i14;

import 'package:awad_nahas/core/error/failure.dart' as _i7;
import 'package:awad_nahas/core/network/network.dart' as _i9;
import 'package:awad_nahas/features/products/data/data_sources/products_remote_data_source.dart'
    as _i10;
import 'package:awad_nahas/features/products/data/models/product_comments.dart'
    as _i8;
import 'package:awad_nahas/features/products/data/models/products_response_model.dart'
    as _i3;
import 'package:awad_nahas/features/products/domain/repositories/products_repository.dart'
    as _i4;
import 'package:awad_nahas/features/products/domain/use_cases/comment_usecase.dart'
    as _i11;
import 'package:awad_nahas/features/products/domain/use_cases/products_usecase.dart'
    as _i12;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductResponseModel_1 extends _i1.SmartFake
    implements _i3.ProductResponseModel {
  _FakeProductResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductsRepository_2 extends _i1.SmartFake
    implements _i4.ProductsRepository {
  _FakeProductsRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_4 extends _i1.SmartFake
    implements _i5.StreamedResponse {
  _FakeStreamedResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepository extends _i1.Mock
    implements _i4.ProductsRepository {
  MockProductsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i3.ProductResponseModel>> getAllProducts(
          {required String? parameter}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [],
          {#parameter: parameter},
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, _i3.ProductResponseModel>>.value(
                _FakeEither_0<_i7.Failure, _i3.ProductResponseModel>(
          this,
          Invocation.method(
            #getAllProducts,
            [],
            {#parameter: parameter},
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i3.ProductResponseModel>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.ProductComments>>>
      getAllProductComments({required Map<String, dynamic>? data}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAllProductComments,
              [],
              {#data: data},
            ),
            returnValue: _i6.Future<
                    _i2.Either<_i7.Failure, List<_i8.ProductComments>>>.value(
                _FakeEither_0<_i7.Failure, List<_i8.ProductComments>>(
              this,
              Invocation.method(
                #getAllProductComments,
                [],
                {#data: data},
              ),
            )),
          ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.ProductComments>>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, bool>> addProductComment(
          {required Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProductComment,
          [],
          {#data: data},
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, bool>>.value(
            _FakeEither_0<_i7.Failure, bool>(
          this,
          Invocation.method(
            #addProductComment,
            [],
            {#data: data},
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, bool>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i9.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> isConnected() => (super.noSuchMethod(
        Invocation.method(
          #isConnected,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [ProductsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRemoteDataSource extends _i1.Mock
    implements _i10.ProductsRemoteDataSource {
  MockProductsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.ProductResponseModel> getAllProducts(
          {required String? parameter}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [],
          {#parameter: parameter},
        ),
        returnValue: _i6.Future<_i3.ProductResponseModel>.value(
            _FakeProductResponseModel_1(
          this,
          Invocation.method(
            #getAllProducts,
            [],
            {#parameter: parameter},
          ),
        )),
      ) as _i6.Future<_i3.ProductResponseModel>);

  @override
  _i6.Future<List<_i8.ProductComments>> getAllProductComments(
          {required Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProductComments,
          [],
          {#data: data},
        ),
        returnValue: _i6.Future<List<_i8.ProductComments>>.value(
            <_i8.ProductComments>[]),
      ) as _i6.Future<List<_i8.ProductComments>>);

  @override
  _i6.Future<bool> addProductComment({required Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProductComment,
          [],
          {#data: data},
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [GetAllProductCommentsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllProductCommentsUseCase extends _i1.Mock
    implements _i11.GetAllProductCommentsUseCase {
  MockGetAllProductCommentsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ProductsRepository get productsRepository => (super.noSuchMethod(
        Invocation.getter(#productsRepository),
        returnValue: _FakeProductsRepository_2(
          this,
          Invocation.getter(#productsRepository),
        ),
      ) as _i4.ProductsRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.ProductComments>>> call(
          {required Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#data: data},
        ),
        returnValue: _i6
            .Future<_i2.Either<_i7.Failure, List<_i8.ProductComments>>>.value(
            _FakeEither_0<_i7.Failure, List<_i8.ProductComments>>(
          this,
          Invocation.method(
            #call,
            [],
            {#data: data},
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.ProductComments>>>);
}

/// A class which mocks [AddProductCommentUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddProductCommentUseCase extends _i1.Mock
    implements _i11.AddProductCommentUseCase {
  MockAddProductCommentUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ProductsRepository get productsRepository => (super.noSuchMethod(
        Invocation.getter(#productsRepository),
        returnValue: _FakeProductsRepository_2(
          this,
          Invocation.getter(#productsRepository),
        ),
      ) as _i4.ProductsRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, bool>> call(
          {required Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#data: data},
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, bool>>.value(
            _FakeEither_0<_i7.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [],
            {#data: data},
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, bool>>);
}

/// A class which mocks [GetAllProductsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllProductsUseCase extends _i1.Mock
    implements _i12.GetAllProductsUseCase {
  MockGetAllProductsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ProductsRepository get productsRepository => (super.noSuchMethod(
        Invocation.getter(#productsRepository),
        returnValue: _FakeProductsRepository_2(
          this,
          Invocation.getter(#productsRepository),
        ),
      ) as _i4.ProductsRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i3.ProductResponseModel>> call(
          {required String? parameter}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#parameter: parameter},
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, _i3.ProductResponseModel>>.value(
                _FakeEither_0<_i7.Failure, _i3.ProductResponseModel>(
          this,
          Invocation.method(
            #call,
            [],
            {#parameter: parameter},
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i3.ProductResponseModel>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i5.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i14.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
      ) as _i6.Future<_i14.Uint8List>);

  @override
  _i6.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i6.Future<_i5.StreamedResponse>.value(_FakeStreamedResponse_4(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i6.Future<_i5.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
