// Mocks generated by Mockito 5.4.2 from annotations
// in awad_nahas/test/features/cart/mockito_data/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i12;
import 'dart:typed_data' as _i13;

import 'package:awad_nahas/core/error/failure.dart' as _i8;
import 'package:awad_nahas/features/cart/data/data_sources/cart_remote_data_source.dart'
    as _i10;
import 'package:awad_nahas/features/cart/data/models/cart_model.dart' as _i4;
import 'package:awad_nahas/features/cart/domain/entities/cart_entity.dart'
    as _i9;
import 'package:awad_nahas/features/cart/domain/repositories/cart_repository.dart'
    as _i6;
import 'package:awad_nahas/features/cart/domain/use_cases/cart_usecase.dart'
    as _i11;
import 'package:awad_nahas/features/order/data/models/coupon_model.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_1 extends _i1.SmartFake implements _i3.Client {
  _FakeClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCartModel_2 extends _i1.SmartFake implements _i4.CartModel {
  _FakeCartModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCouponModel_3 extends _i1.SmartFake implements _i5.CouponModel {
  _FakeCouponModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCartRepository_4 extends _i1.SmartFake
    implements _i6.CartRepository {
  _FakeCartRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_5 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_6 extends _i1.SmartFake
    implements _i3.StreamedResponse {
  _FakeStreamedResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i6.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i9.CartEntity>> getAllCartList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCartList,
          [],
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, _i9.CartEntity>>.value(
            _FakeEither_0<_i8.Failure, _i9.CartEntity>(
          this,
          Invocation.method(
            #getAllCartList,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, _i9.CartEntity>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, bool>> addCartItem(
          {required Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCartItem,
          [],
          {#data: data},
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, bool>>.value(
            _FakeEither_0<_i8.Failure, bool>(
          this,
          Invocation.method(
            #addCartItem,
            [],
            {#data: data},
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, bool>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, bool>> removeCartItem(
          {required int? productID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeCartItem,
          [],
          {#productID: productID},
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, bool>>.value(
            _FakeEither_0<_i8.Failure, bool>(
          this,
          Invocation.method(
            #removeCartItem,
            [],
            {#productID: productID},
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, bool>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i5.CouponModel>> applyCoupon(
          {required Map<String, dynamic>? dataSet}) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyCoupon,
          [],
          {#dataSet: dataSet},
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, _i5.CouponModel>>.value(
            _FakeEither_0<_i8.Failure, _i5.CouponModel>(
          this,
          Invocation.method(
            #applyCoupon,
            [],
            {#dataSet: dataSet},
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, _i5.CouponModel>>);
}

/// A class which mocks [CartRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRemoteDataSource extends _i1.Mock
    implements _i10.CartRemoteDataSource {
  MockCartRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_1(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.Client);

  @override
  _i7.Future<bool> addCartItem({required Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCartItem,
          [],
          {#data: data},
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i4.CartModel> fetchAllCartList() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllCartList,
          [],
        ),
        returnValue: _i7.Future<_i4.CartModel>.value(_FakeCartModel_2(
          this,
          Invocation.method(
            #fetchAllCartList,
            [],
          ),
        )),
      ) as _i7.Future<_i4.CartModel>);

  @override
  _i7.Future<bool> removeCartItem({required int? productID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeCartItem,
          [],
          {#productID: productID},
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i5.CouponModel> applyCoupon(
          {required Map<String, dynamic>? dataSet}) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyCoupon,
          [],
          {#dataSet: dataSet},
        ),
        returnValue: _i7.Future<_i5.CouponModel>.value(_FakeCouponModel_3(
          this,
          Invocation.method(
            #applyCoupon,
            [],
            {#dataSet: dataSet},
          ),
        )),
      ) as _i7.Future<_i5.CouponModel>);
}

/// A class which mocks [AddCartItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddCartItemUseCase extends _i1.Mock
    implements _i11.AddCartItemUseCase {
  MockAddCartItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CartRepository get cartRepository => (super.noSuchMethod(
        Invocation.getter(#cartRepository),
        returnValue: _FakeCartRepository_4(
          this,
          Invocation.getter(#cartRepository),
        ),
      ) as _i6.CartRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, bool>> call(
          {required Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#data: data},
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, bool>>.value(
            _FakeEither_0<_i8.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [],
            {#data: data},
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, bool>>);
}

/// A class which mocks [GetAllCartListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCartListUseCase extends _i1.Mock
    implements _i11.GetAllCartListUseCase {
  MockGetAllCartListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CartRepository get cartRepository => (super.noSuchMethod(
        Invocation.getter(#cartRepository),
        returnValue: _FakeCartRepository_4(
          this,
          Invocation.getter(#cartRepository),
        ),
      ) as _i6.CartRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i9.CartEntity>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, _i9.CartEntity>>.value(
            _FakeEither_0<_i8.Failure, _i9.CartEntity>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, _i9.CartEntity>>);
}

/// A class which mocks [RemoveCartItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveCartItemUseCase extends _i1.Mock
    implements _i11.RemoveCartItemUseCase {
  MockRemoveCartItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CartRepository get cartRepository => (super.noSuchMethod(
        Invocation.getter(#cartRepository),
        returnValue: _FakeCartRepository_4(
          this,
          Invocation.getter(#cartRepository),
        ),
      ) as _i6.CartRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, bool>> call({required int? productID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#productID: productID},
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, bool>>.value(
            _FakeEither_0<_i8.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [],
            {#productID: productID},
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, bool>>);
}

/// A class which mocks [ApplyCouponUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockApplyCouponUseCase extends _i1.Mock
    implements _i11.ApplyCouponUseCase {
  MockApplyCouponUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CartRepository get cartRepository => (super.noSuchMethod(
        Invocation.getter(#cartRepository),
        returnValue: _FakeCartRepository_4(
          this,
          Invocation.getter(#cartRepository),
        ),
      ) as _i6.CartRepository);

  @override
  set cartRepository(_i6.CartRepository? _cartRepository) => super.noSuchMethod(
        Invocation.setter(
          #cartRepository,
          _cartRepository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i5.CouponModel>> call(
          {required Map<String, dynamic>? dataSet}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#dataSet: dataSet},
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, _i5.CouponModel>>.value(
            _FakeEither_0<_i8.Failure, _i5.CouponModel>(
          this,
          Invocation.method(
            #call,
            [],
            {#dataSet: dataSet},
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, _i5.CouponModel>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i3.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i3.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<_i3.Response>);

  @override
  _i7.Future<_i3.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i3.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<_i3.Response>);

  @override
  _i7.Future<_i3.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i3.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i3.Response>);

  @override
  _i7.Future<_i3.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i3.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i3.Response>);

  @override
  _i7.Future<_i3.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i3.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i3.Response>);

  @override
  _i7.Future<_i3.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i3.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i3.Response>);

  @override
  _i7.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);

  @override
  _i7.Future<_i13.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
      ) as _i7.Future<_i13.Uint8List>);

  @override
  _i7.Future<_i3.StreamedResponse> send(_i3.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i7.Future<_i3.StreamedResponse>.value(_FakeStreamedResponse_6(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i7.Future<_i3.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
