// Mocks generated by Mockito 5.4.4 from annotations
// in awad_nahas/test/features/cart/mockito_data/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:convert' as _i14;
import 'dart:typed_data' as _i16;

import 'package:awad_nahas/core/error/failure.dart' as _i10;
import 'package:awad_nahas/features/cart/data/data_sources/cart_remote_data_source.dart'
    as _i12;
import 'package:awad_nahas/features/cart/data/models/cart_model.dart' as _i4;
import 'package:awad_nahas/features/cart/domain/entities/cart_entity.dart'
    as _i11;
import 'package:awad_nahas/features/cart/domain/repositories/cart_repository.dart'
    as _i6;
import 'package:awad_nahas/features/cart/domain/use_cases/cart_usecase.dart'
    as _i13;
import 'package:awad_nahas/features/order/data/models/coupon_model.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter/foundation.dart' as _i8;
import 'package:flutter/material.dart' as _i7;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_1 extends _i1.SmartFake implements _i3.Client {
  _FakeClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCartModel_2 extends _i1.SmartFake implements _i4.CartModel {
  _FakeCartModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCouponModel_3 extends _i1.SmartFake implements _i5.CouponModel {
  _FakeCouponModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCartRepository_4 extends _i1.SmartFake
    implements _i6.CartRepository {
  _FakeCartRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_5 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_6 extends _i1.SmartFake
    implements _i3.StreamedResponse {
  _FakeStreamedResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_7 extends _i1.SmartFake implements _i7.Widget {
  _FakeWidget_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_8 extends _i1.SmartFake
    implements _i7.InheritedWidget {
  _FakeInheritedWidget_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_9 extends _i1.SmartFake
    implements _i7.DiagnosticsNode {
  _FakeDiagnosticsNode_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i8.TextTreeConfiguration? parentConfiguration,
    _i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info,
  }) =>
      super.toString();
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i6.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i11.CartEntity>> getAllCartList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCartList,
          [],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i11.CartEntity>>.value(
                _FakeEither_0<_i10.Failure, _i11.CartEntity>(
          this,
          Invocation.method(
            #getAllCartList,
            [],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i11.CartEntity>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, bool>> addCartItem(
          {required Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCartItem,
          [],
          {#data: data},
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, bool>>.value(
            _FakeEither_0<_i10.Failure, bool>(
          this,
          Invocation.method(
            #addCartItem,
            [],
            {#data: data},
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, bool>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, bool>> removeCartItem(
          {required int? productID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeCartItem,
          [],
          {#productID: productID},
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, bool>>.value(
            _FakeEither_0<_i10.Failure, bool>(
          this,
          Invocation.method(
            #removeCartItem,
            [],
            {#productID: productID},
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, bool>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i5.CouponModel>> applyCoupon(
          {required Map<String, dynamic>? dataSet}) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyCoupon,
          [],
          {#dataSet: dataSet},
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i5.CouponModel>>.value(
                _FakeEither_0<_i10.Failure, _i5.CouponModel>(
          this,
          Invocation.method(
            #applyCoupon,
            [],
            {#dataSet: dataSet},
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i5.CouponModel>>);
}

/// A class which mocks [CartRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRemoteDataSource extends _i1.Mock
    implements _i12.CartRemoteDataSource {
  MockCartRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_1(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.Client);

  @override
  _i9.Future<bool> addCartItem({required Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCartItem,
          [],
          {#data: data},
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<_i4.CartModel> fetchAllCartList() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllCartList,
          [],
        ),
        returnValue: _i9.Future<_i4.CartModel>.value(_FakeCartModel_2(
          this,
          Invocation.method(
            #fetchAllCartList,
            [],
          ),
        )),
      ) as _i9.Future<_i4.CartModel>);

  @override
  _i9.Future<bool> removeCartItem({required int? productID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeCartItem,
          [],
          {#productID: productID},
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<_i5.CouponModel> applyCoupon(
          {required Map<String, dynamic>? dataSet}) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyCoupon,
          [],
          {#dataSet: dataSet},
        ),
        returnValue: _i9.Future<_i5.CouponModel>.value(_FakeCouponModel_3(
          this,
          Invocation.method(
            #applyCoupon,
            [],
            {#dataSet: dataSet},
          ),
        )),
      ) as _i9.Future<_i5.CouponModel>);
}

/// A class which mocks [AddCartItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddCartItemUseCase extends _i1.Mock
    implements _i13.AddCartItemUseCase {
  MockAddCartItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CartRepository get cartRepository => (super.noSuchMethod(
        Invocation.getter(#cartRepository),
        returnValue: _FakeCartRepository_4(
          this,
          Invocation.getter(#cartRepository),
        ),
      ) as _i6.CartRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, bool>> call(
          {required Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#data: data},
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, bool>>.value(
            _FakeEither_0<_i10.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [],
            {#data: data},
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, bool>>);
}

/// A class which mocks [GetAllCartListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCartListUseCase extends _i1.Mock
    implements _i13.GetAllCartListUseCase {
  MockGetAllCartListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CartRepository get cartRepository => (super.noSuchMethod(
        Invocation.getter(#cartRepository),
        returnValue: _FakeCartRepository_4(
          this,
          Invocation.getter(#cartRepository),
        ),
      ) as _i6.CartRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i11.CartEntity>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i11.CartEntity>>.value(
                _FakeEither_0<_i10.Failure, _i11.CartEntity>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i11.CartEntity>>);
}

/// A class which mocks [RemoveCartItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveCartItemUseCase extends _i1.Mock
    implements _i13.RemoveCartItemUseCase {
  MockRemoveCartItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CartRepository get cartRepository => (super.noSuchMethod(
        Invocation.getter(#cartRepository),
        returnValue: _FakeCartRepository_4(
          this,
          Invocation.getter(#cartRepository),
        ),
      ) as _i6.CartRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, bool>> call({required int? productID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#productID: productID},
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, bool>>.value(
            _FakeEither_0<_i10.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [],
            {#productID: productID},
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, bool>>);
}

/// A class which mocks [ApplyCouponUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockApplyCouponUseCase extends _i1.Mock
    implements _i13.ApplyCouponUseCase {
  MockApplyCouponUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CartRepository get cartRepository => (super.noSuchMethod(
        Invocation.getter(#cartRepository),
        returnValue: _FakeCartRepository_4(
          this,
          Invocation.getter(#cartRepository),
        ),
      ) as _i6.CartRepository);

  @override
  set cartRepository(_i6.CartRepository? _cartRepository) => super.noSuchMethod(
        Invocation.setter(
          #cartRepository,
          _cartRepository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i5.CouponModel>> call(
          {required Map<String, dynamic>? dataSet}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#dataSet: dataSet},
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i5.CouponModel>>.value(
                _FakeEither_0<_i10.Failure, _i5.CouponModel>(
          this,
          Invocation.method(
            #call,
            [],
            {#dataSet: dataSet},
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i5.CouponModel>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i3.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i3.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<_i3.Response>);

  @override
  _i9.Future<_i3.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i3.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<_i3.Response>);

  @override
  _i9.Future<_i3.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i14.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i3.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i3.Response>);

  @override
  _i9.Future<_i3.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i14.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i3.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i3.Response>);

  @override
  _i9.Future<_i3.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i14.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i3.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i3.Response>);

  @override
  _i9.Future<_i3.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i14.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i3.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i3.Response>);

  @override
  _i9.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i16.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i16.Uint8List>.value(_i16.Uint8List(0)),
      ) as _i9.Future<_i16.Uint8List>);

  @override
  _i9.Future<_i3.StreamedResponse> send(_i3.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i9.Future<_i3.StreamedResponse>.value(_FakeStreamedResponse_6(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i9.Future<_i3.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i7.BuildContext {
  @override
  _i7.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_7(
          this,
          Invocation.getter(#widget),
        ),
        returnValueForMissingStub: _FakeWidget_7(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i7.Widget);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.InheritedWidget dependOnInheritedElement(
    _i7.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_8(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
        returnValueForMissingStub: _FakeInheritedWidget_8(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i7.InheritedWidget);

  @override
  void visitAncestorElements(_i7.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i7.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchNotification(_i7.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.DiagnosticsNode describeElement(
    String? name, {
    _i8.DiagnosticsTreeStyle? style = _i8.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_9(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_9(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i7.DiagnosticsNode);

  @override
  _i7.DiagnosticsNode describeWidget(
    String? name, {
    _i8.DiagnosticsTreeStyle? style = _i8.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_9(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_9(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i7.DiagnosticsNode);

  @override
  List<_i7.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i7.DiagnosticsNode>[],
        returnValueForMissingStub: <_i7.DiagnosticsNode>[],
      ) as List<_i7.DiagnosticsNode>);

  @override
  _i7.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_9(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_9(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i7.DiagnosticsNode);
}
